""" creating tables

Revision ID: 0d7e9c3224c7
Revises: 
Create Date: 2021-05-05 17:59:38.338687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7e9c3224c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('creatorUserId', sa.Integer(), nullable=True))
    op.drop_constraint('events_hostId_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['creatorUserId'], ['id'])
    op.drop_column('events', 'hostId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('hostId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_hostId_fkey', 'events', 'users', ['hostId'], ['id'])
    op.drop_column('events', 'creatorUserId')
    # ### end Alembic commands ###
