"""empty message

Revision ID: 656a7bda5613
Revises: 
Create Date: 2021-05-12 00:41:14.911894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656a7bda5613'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('someoneBringing', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'someoneBringing')
    # ### end Alembic commands ###
