"""empty message

Revision ID: d2288307b9ec
Revises: ed6b650f7875
Create Date: 2021-05-04 19:12:21.835555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2288307b9ec'
down_revision = 'ed6b650f7875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostName', sa.String(length=50), nullable=False),
    sa.Column('hostContact', sa.String(length=250), nullable=True),
    sa.Column('hostEmail', sa.String(length=200), nullable=False),
    sa.Column('hostURL', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('locationName', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('startTime', sa.Time(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('totalCost', sa.DECIMAL(asdecimal=False), nullable=True),
    sa.Column('availableSpots', sa.Integer(), nullable=True),
    sa.Column('thingsNeeded', sa.Text(), nullable=True),
    sa.Column('hostId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hostId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
