"""create tables

Revision ID: efc332f20eb4
Revises: 
Create Date: 2021-05-05 01:42:58.650121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc332f20eb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contactInfo', sa.String(length=250), nullable=True),
    sa.Column('attendeeEmail', sa.String(length=200), nullable=False),
    sa.Column('attendeeURL', sa.Text(), nullable=False),
    sa.Column('going', sa.Boolean(), nullable=True),
    sa.Column('eventId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendees')
    # ### end Alembic commands ###
